### ISSUE TITLE
Confusion caused by the word 'Transformer'

### ISSUE THREAD

**Issue by RachitBansal** [clips/wordkit#19]
The word 'Transformer' has been used extensively throughout the module. This terminology is a cause of great confusion because the same term is used for the Transformer Model introduced in [Attention is all you need](https://arxiv.org/abs/1706.03762) which has been popular for various NLP applications in the past years. Though, that's not what the term means to refer to here.

**Comment by stephantul** [comment]
The term transformer is used in the same way in the `sklearn` library. See: https://scikit-learn.org/stable/modules/generated/sklearn.base.TransformerMixin.html#sklearn.base.TransformerMixin. Originally, the transformers in wordkit inherited from the transformer base class in `sklearn`. They are still fully compatible with the `sklearn` transformer API. All this is to say that I think the usage of the term transformer is justified in this case.

In any case, name collisions are to be expected if you go through code bases and/or scientific papers, especially if you switch between fields.
